<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Constants -->
    <xacro:property name="LENGTH" value="1.0"/>    
    <xacro:property name="WIDTH" value="0.1"/>    
    <xacro:property name="HEIGHT" value="0.1"/>
    <xacro:property name="RADIUS" value="${WIDTH / 2.0}"/>
</robot>
