manipulator:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 45
    
    manipulator_trajectory_controller:
        type: position_controllers/JointTrajectoryController
        joints: 
          - joint1
          - joint2
